name: GitHub CI build

# GITHUB_REF_NAME in the form of release-$VERSION-$RELEASE-$EXTRA_NAME

on:
  push:
    tags:
      - release-**-**-**
  workflow_dispatch:

env:
  RELEASESDK: 4.5.0.16

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 20480
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-haskell: 'true'
        remove-android: 'true'
        remove-docker-images: 'true'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build mic
      run:  |
        export VERSION=$(echo $GITHUB_REF_NAME | cut -d "-" -f 2)
        export RELEASE=$(echo $GITHUB_REF_NAME | cut -d "-" -f 3)
        export EXTRA_NAME=-$(echo $GITHUB_REF_NAME | cut -d "-" -f 4-)
        docker run --rm --privileged --mount type=bind,src=$PWD,dst=/share --mount type=bind,src=/data,dst=/data --env-file env.list -e VERSION -e RELEASE -e EXTRA_NAME coderus/sailfishos-platform-sdk:$RELEASESDK /bin/bash -c "
            /share/scripts/create-image.sh --release $RELEASE --version $VERSION ;"

    - name: Update release
      run: |
        gh release create ${{ github.ref_name }} || true
        gh release upload ${{ github.ref_name }} build/mic/sfe-*/*.tar.bz2 --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
